name: Release

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
    inputs:
      isRelease:
        description: 'Is this a release? yes or no'
        required: true
        default: 'no'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4.0.0
      with:
        node-version: 18.16.0
        registry-url: 'https://registry.npmjs.org'
    - name: Install Node.js dependencies
      run: npm install
    - name: Build release ${{ github.event.inputs.version }}
      working-directory: packages/vscode-extension
      run: |
        if [ "${{ github.event.inputs.isRelease }}" != "yes" ]; then
          node ./version.cjs
        fi
        npx vsce package
        ls -lsh ./
    - name: Upload release to artifact
      uses: actions/upload-artifact@v2
      with:
        name: jsar-devtools
        path: './dist'
